# Numpy 2차원데이터

## 다양한 indexing 방법

In [1]:
import numpy as np

data = np.array([[1,2,3],
                 [7,5,2],
                 [10,1,8],
                 [6,3,4]])

print(data)
print(data.shape)
print(data[1])
print(data[1,1])
print(data[[0,2,3]]) # 0,2,3 번째 행 
print(data[1:3,1])
print(data[1:,[0,2]])


[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]
(4, 3)
[7 5 2]
5
[[ 1  2  3]
 [10  1  8]
 [ 6  3  4]]
[5 1]
[[ 7  2]
 [10  8]
 [ 6  4]]


## 다양한 계산법
행렬 중에 언급이 없으면 행부터

In [2]:
data = np.array([[1,2,3],
                 [7,5,2],
                 [10,1,8],
                 [6,3,4]])

print(data)
print("-----------")

print(data + 2)
print("-----------")

data[1] += 2 # 1번째 행에 2씩 더함
print(data)



[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]
-----------
[[ 3  4  5]
 [ 9  7  4]
 [12  3 10]
 [ 8  5  6]]
-----------
[[ 1  2  3]
 [ 9  7  4]
 [10  1  8]
 [ 6  3  4]]


## 다양한 추가 방법
- axis=0: 행
- axis=1: 열
- axis=1인 경우, ax내용을 일단 열에 배치하고 ay 추가

In [3]:
ax = np.array([[1,2],[3,4]])
ay = np.array([[5,6],[7,8]])

# 1차원으로 풀어서
print(np.append(ax,ay, axis=None))
print("----------------")

# row(행)에 추가
print(np.append(ax, ay, axis =0))
print("----------------")

# column(열)에 추가
print(np.append(ax, ay, axis =1))
print("----------------")


[1 2 3 4 5 6 7 8]
----------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------------
[[1 2 5 6]
 [3 4 7 8]]
----------------


## 다양한 삭제/정렬 방법
- axis=0: 행
- axis=1: 열

In [4]:
data = np.array([[1,2,3],
                 [7,5,2],
                 [10,1,8],
                 [6,3,4]])

print(data)
print(np.delete(data,[0,2]))
print(np.delete(data,[0,2], axis=0)) # 행 삭제 
print(np.delete(data,[0,2], axis=1)) # 열 삭제
print(np.sort(data, axis=None))


[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]
[ 2  7  5  2 10  1  8  6  3  4]
[[7 5 2]
 [6 3 4]]
[[2]
 [5]
 [1]
 [3]]
[ 1  1  2  2  3  3  4  5  6  7  8 10]


## 다양한 합/평균
axis=0/1에 따라 행/렬이 바뀜에 주의

In [5]:
data = np.array([[1,2,3],
                 [7,5,2],
                 [10,1,8],
                 [6,3,4]])

# 다양한 합/평균 axis =0/1 에 따라 행/렬이 바뀜
print(data)
print(data.sum(axis=0)) # 열 별 통계값
print(data.sum(axis=1)) # 행 별 통계값
print(data.sum())
print("-------------")

print(data.mean(axis=0))
print(data.mean(axis=1))
print("-------------")

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]
[24 11 17]
[ 6 14 19 13]
52
-------------
[6.   2.75 4.25]
[2.         4.66666667 6.33333333 4.33333333]
-------------


## 다양한 최대 계산

In [6]:
data = np.array([[1,2,3],
                 [7,5,2],
                 [10,1,8],
                 [6,3,4]])

print(data)
print(np.max(data))
print(data.argmax())
print(data.argmax(axis=0)) # 열에서 가장 큰 값의 index 값 
print(data.argmax(axis=1)) # 행에서 가장 큰 값의 index 값
print("---------------")

for a, b, c in data:
    print(a,b,c)

[[ 1  2  3]
 [ 7  5  2]
 [10  1  8]
 [ 6  3  4]]
10
6
[2 1 2]
[2 0 0 0]
---------------
1 2 3
7 5 2
10 1 8
6 3 4


## 다양한 수학연산

In [7]:
arr = np.array([[-1.2, -1.3, 0.3],
                [0.9, 0.4, 0],
                [0.5, 0.3, -.1], 
                [0.7, -3.1, 0.8], 
                [0.4, 1.2, 0.5]])

print(arr)
print(np.abs(arr)) # 절댓값
print(np.sqrt(arr)) # 제곱근 == arr ** 0.5
print(np.square(arr)) # 제곱

[[-1.2 -1.3  0.3]
 [ 0.9  0.4  0. ]
 [ 0.5  0.3 -0.1]
 [ 0.7 -3.1  0.8]
 [ 0.4  1.2  0.5]]
[[1.2 1.3 0.3]
 [0.9 0.4 0. ]
 [0.5 0.3 0.1]
 [0.7 3.1 0.8]
 [0.4 1.2 0.5]]
[[       nan        nan 0.54772256]
 [0.9486833  0.63245553 0.        ]
 [0.70710678 0.54772256        nan]
 [0.83666003        nan 0.89442719]
 [0.63245553 1.09544512 0.70710678]]
[[1.44 1.69 0.09]
 [0.81 0.16 0.  ]
 [0.25 0.09 0.01]
 [0.49 9.61 0.64]
 [0.16 1.44 0.25]]


C:\Users\Leesm\AppData\Local\Temp\ipykernel_18456\1680953225.py:9: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr)) # 제곱근 == arr ** 0.5


In [8]:
arr = np.array([[-1.2, -1.3, 0.3],
                [0.9, 0.4, 0],
                [0.5, 0.3, -.1], 
                [0.7, -3.1, 0.8], 
                [0.4, 1.2, 0.5]])

print(arr)
print(np.exp(arr))
print(np.log(arr)) # 상용로그
print(np.log10(arr)) 

[[-1.2 -1.3  0.3]
 [ 0.9  0.4  0. ]
 [ 0.5  0.3 -0.1]
 [ 0.7 -3.1  0.8]
 [ 0.4  1.2  0.5]]
[[0.30119421 0.27253179 1.34985881]
 [2.45960311 1.4918247  1.        ]
 [1.64872127 1.34985881 0.90483742]
 [2.01375271 0.0450492  2.22554093]
 [1.4918247  3.32011692 1.64872127]]
[[        nan         nan -1.2039728 ]
 [-0.10536052 -0.91629073        -inf]
 [-0.69314718 -1.2039728          nan]
 [-0.35667494         nan -0.22314355]
 [-0.91629073  0.18232156 -0.69314718]]
[[        nan         nan -0.52287875]
 [-0.04575749 -0.39794001        -inf]
 [-0.30103    -0.52287875         nan]
 [-0.15490196         nan -0.09691001]
 [-0.39794001  0.07918125 -0.30103   ]]


C:\Users\Leesm\AppData\Local\Temp\ipykernel_18456\3019650080.py:9: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr)) # 상용로그
C:\Users\Leesm\AppData\Local\Temp\ipykernel_18456\3019650080.py:9: RuntimeWarning: invalid value encountered in log
  print(np.log(arr)) # 상용로그
C:\Users\Leesm\AppData\Local\Temp\ipykernel_18456\3019650080.py:10: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(arr))
C:\Users\Leesm\AppData\Local\Temp\ipykernel_18456\3019650080.py:10: RuntimeWarning: invalid value encountered in log10
  print(np.log10(arr))


In [9]:
arr = np.array([[-1.2, -1.3, 0.3],
                [0.9, 0.4, 0],
                [0.5, 0.3, -.1], 
                [0.7, -3.1, 0.8], 
                [0.4, 1.2, 0.5]])

print(arr)
print(np.sign(arr)) # 부호 출력
print(np.ceil(arr)) # 올림
print(np.floor(arr)) # 내림

[[-1.2 -1.3  0.3]
 [ 0.9  0.4  0. ]
 [ 0.5  0.3 -0.1]
 [ 0.7 -3.1  0.8]
 [ 0.4  1.2  0.5]]
[[-1. -1.  1.]
 [ 1.  1.  0.]
 [ 1.  1. -1.]
 [ 1. -1.  1.]
 [ 1.  1.  1.]]
[[-1. -1.  1.]
 [ 1.  1.  0.]
 [ 1.  1. -0.]
 [ 1. -3.  1.]
 [ 1.  2.  1.]]
[[-2. -2.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]
 [ 0. -4.  0.]
 [ 0.  1.  0.]]


In [10]:
arr = np.array([[-1.2, -1.3, 0.3],
                [0.9, 0.4, 0],
                [0.5, 0.3, -.1], 
                [0.7, -3.1, 0.8], 
                [0.4, 1.2, 0.5]])

print(arr)
print(np.sin(arr))
print(np.tanh(arr))
print("-------------")

# 각 성분이 NaN인 경우 True를, 안니 경우 False를 반환
print(np.isnan(arr))
print(np.isnan(np.log(arr)))
print("-------------")

# 각 성분이 무한대인 경우 True를, 아닌 경우 False를 반환
print(np.isinf(arr))

[[-1.2 -1.3  0.3]
 [ 0.9  0.4  0. ]
 [ 0.5  0.3 -0.1]
 [ 0.7 -3.1  0.8]
 [ 0.4  1.2  0.5]]
[[-0.93203909 -0.96355819  0.29552021]
 [ 0.78332691  0.38941834  0.        ]
 [ 0.47942554  0.29552021 -0.09983342]
 [ 0.64421769 -0.04158066  0.71735609]
 [ 0.38941834  0.93203909  0.47942554]]
[[-0.83365461 -0.86172316  0.29131261]
 [ 0.71629787  0.37994896  0.        ]
 [ 0.46211716  0.29131261 -0.09966799]
 [ 0.60436778 -0.99594936  0.66403677]
 [ 0.37994896  0.83365461  0.46211716]]
-------------
[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]
[[ True  True False]
 [False False False]
 [False False  True]
 [False  True False]
 [False False False]]
-------------
[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]


C:\Users\Leesm\AppData\Local\Temp\ipykernel_18456\4019157603.py:14: RuntimeWarning: divide by zero encountered in log
  print(np.isnan(np.log(arr)))
C:\Users\Leesm\AppData\Local\Temp\ipykernel_18456\4019157603.py:14: RuntimeWarning: invalid value encountered in log
  print(np.isnan(np.log(arr)))
