# Numpy

In [1]:
import numpy as np

## Numpy shape
- shape을 통해 해당 array의 크기를 알 수 있음
- shape을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인가능
- arr1.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을확인
- 콤마 다음에 아무것도 없다는 것은 1차원이라는 뜻 (5, 1)

In [2]:
data1 = [1, 2, 3, 4, 5]
data2 = [1, 2, 3, 3.5, 4]

arr1 = np.array(data1)
print(arr1)
print(arr1.shape) # .shape - > (데이터 수,) 1차원
print("---------------------")

arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)
print(arr2.shape)
print(arr2.dtype) # 데이터 타입

[1 2 3 4 5]
(5,)
---------------------
[1 2 3 4 5]
(5,)
int32


- arr3.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 확인
- arr4.shape 는 (4, 3)으로 2차원

In [3]:
data1 = [1, 2, 3, 4, 5]
data2 = [1, 2, 3, 3.5, 5]

arr3 = np.array(data2)
print(arr3)
print(arr3.shape)
print(arr3.dtype)
print("------------------")

arr4 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr4)
print(arr4.shape)


[1.  2.  3.  3.5 5. ]
(5,)
float64
------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


## np.zeros() 함수
인자로 받는 크기만큼, 모든요소가 0인 array를 만듬
## np.ones() 함수
인자로 받는 크기만큼, 모든요소가 1인 array를 만듬
## np.arange() 함수
인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만듬. 
이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가짐

In [4]:
print(np.zeros(10))
print(np.zeros((3,5)))
print("----------------")

print(np.ones(9))
print(np.ones((2,10)))
print("--------------------")

print(np.arange(10))
print(np.arange(3,10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----------------
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
--------------------
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]


## Array 연산
- 기본적으로 numpy에서 연산을 할 때는 크기가 서로 동일한 array 끼리 연산이 진행
- 이때 같은 위치에 있는 요소들 끼리 연산이 진행 (물론, array의 [브로드 캐스트]라고 해서 크기가 달라고 연산이 되지만 지양)
- array 곱셈은, (주의) 행렬의 곱처럼 곱셈이 진행되는 것이 아니라 각 요소별로 곱셈이 진행

In [5]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1.shape)

arr2 = np.array([[10,11,12], [13,14,15]])
print(arr2.shape)
print("---------------------")

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


(2, 3)
(2, 3)
---------------------
[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[10 22 36]
 [52 70 90]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]]


## Array 인덱싱
- numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일
- 즉, 시작은 1번째로 시작하는 것이 아니라 0번째로 시작

In [6]:
arr1 = np.arange(10)
print(arr1[0])
print(arr1[4:])
print(arr1[-1])
print("-------------")

arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print(arr2[2,3])
print(arr2[:,3]) # : --> 행 부분 전체

0
[4 5 6 7 8 9]
9
-------------
12
[ 4  8 12]


## arrange 응용
 randint는 integer의 임의의 random 수를 반환

In [7]:
# 1부터 10까지 1식 증가
arr3 = np.arange(1,11,1)
print(arr3)

# 1부터 10까지 2식 증가
arr4 = np.arange(1,11,2)
print(arr4)

# 1부터 10까지 5개를 랜덤으로 뽑아 1차원 행렬
arr5 = np.random.randint(1,11,size=5)
print(arr5)

# 1부터 10까지 (3,2)인 2차원 행렬
arr6 = np.random.randint(1,11,size=(3,2))
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 6 10  2  3  2]
[[ 5  6]
 [10  5]
 [ 3  6]]


## np.random 함수들
#### np.random.rand() 
0~1 사이의 random number
#### np.random.randn()
0~1 사이의 random number 이기는 한데,
평균이 0이고 편차가 1인 표준정규분포만족
#### np.random.choice()
임의로 2번째 parameter 개수만큼 선택

In [8]:
# rand --> 0~1 사이 실수값 반환
print(np.random.rand(5))
print(np.random.rand(2,3))

# randn --> 표준정규분포 (평균0, 편차1)
print(np.random.randn(5)) 
print(np.random.randn(2,3))

# [1, 2, 3, 4, 5] 중에 1개를 임의로 선택 
print(np.random.choice([1, 2, 3, 4, 5], 1))

# 1~10 중에 5개를 임의로 선택
print(np.random.choice(np.arange(1,11),5))

[0.34601526 0.74309652 0.95505143 0.93130749 0.82051763]
[[0.00919358 0.55394348 0.86693803]
 [0.50194965 0.11678767 0.86822697]]
[0.52389717 0.33008268 0.8699815  0.26854387 0.23770183]
[[-0.34738408 -0.02873094 -1.21578535]
 [ 0.59189774  0.69795735  0.26777916]]
[5]
[ 1  1 10  4  3]


## numpy.unique() 
#### 고유한 것들만 추출하는 기능
- return_index = True 인 경우 각 고유 값이 처음 나타나는 인덱스 배열을 반환
- return_counts = True 이면 입력 배열의 각 고유 값의 개수 배열을 반환
- return_inverse = True이면 고유 배열의 인덱스를 반환하며 입력 배열을 재구성

In [9]:
a = np.array([[2,3,4],
              [5,4,7],
              [4,2,3]])

print(np.unique(a))

print(np.unique(a, return_index=True)) # 배열 인덱스

v, c = np.unique(a, return_index=True)
print(v)
print(c)
print("------------------")

print(np.unique(a, return_counts=True)) # 배열의 각 고유 값의 개수 
print(np.unique(a, return_inverse=True)) # 고유의 값이 5개여서 인덱스 값을 0~4로 재구성

[2 3 4 5 7]
(array([2, 3, 4, 5, 7]), array([0, 1, 2, 3, 5], dtype=int64))
[2 3 4 5 7]
[0 1 2 3 5]
------------------
(array([2, 3, 4, 5, 7]), array([2, 2, 3, 1, 1], dtype=int64))
(array([2, 3, 4, 5, 7]), array([0, 1, 2, 3, 2, 4, 2, 0, 1], dtype=int64))


#### 작은것에서 큰 것으로 오름차순으로 나옴
- axis=0 # 고유한 행
- axis=1 # 고유한 열

In [10]:
a = np.array([[2,3,2],
              [2,3,2], 
              [4,2,3]])
 
print(np.unique(a, axis= 0)) # 종복 제거
print("--------------------")

b = np.array([[2,3,2],
              [2,3,2],
              [3,2,3]])

print(np.unique(b, axis=1)) # 중복 제거

c = np.array([[2,3,2],
              [2,3,3],
              [3,2,3]])

print(np.unique(c, axis=1)) # 오름차순으로 나옴 2번째 열이 마지막으로 이동

[[2 3 2]
 [4 2 3]]
--------------------
[[2 3]
 [2 3]
 [3 2]]
[[2 2 3]
 [2 3 3]
 [3 3 2]]


## numpy.zip()
묶는 기능

In [11]:
v, c = np.unique([1, 2, 2, 3, 3, 3, 4, 4, 5], return_counts=True)
print(v)
print(c)

for a, b in zip(v, c):
    print(a, b)

[1 2 3 4 5]
[1 2 3 2 1]
1 1
2 2
3 3
4 2
5 1


## 전치행렬(transpose)
- 행과 열을 바꾼 행렬
- 행렬곱 등을 할 때, AM x MB 와 같이 M이 맞지 않을 때,
- 강제로 수정 등을 위해 사용

In [12]:
arr1 = np.array([[11, 22],
                 [33, 44],
                 [55, 66]])

print(arr1.dtype)
print(arr1.size)
print(arr1.shape)

print(arr1.T) # transpose 전치행렬 : 행 <-> 열 
print(arr1.T.shape)

int32
6
(3, 2)
[[11 33 55]
 [22 44 66]]
(2, 3)


## 형변환 astype
- 데이터분석에서 많이 사용
- 예를들어 전화번호를 문자로 할 것이냐 숫자로 할 것이냐? 등
- astype을 사용
- 행과 열을 바꾼 행렬
- -1을 쓰면 알아서 맞춤

In [13]:
arr = np.array([11, 22, 33, 44, 55])
print(arr.dtype)

arr = arr.astype(np.float32) # arr를 float로 변환
print(arr.dtype)

arr2 =  arr.resize(3,2) # 값이 부족
print(arr2)

arr3 = arr.reshape(-1, 2) # -1 : 알아서 결정, 없으면 채움 
print(arr3)

int32
float32
None
[[11. 22.]
 [33. 44.]
 [55.  0.]]


## Boolean indexing (element-wise)
조건을 주어서, 해당 인덱스만 추출하는 기능

In [14]:
arr1 = np.array([11, 22, 33, 44, 55])
print(arr1)

arr2 = arr1[[True, True, False, False, True]]
print(arr2)

print(arr1 > 30)
print(arr1[arr1 > 30])

[11 22 33 44 55]
[11 22 55]
[False False  True  True  True]
[33 44 55]


## 인덱스에 추가/삭제
#### append 함수
항상 마지막 인덱스에 배열을 추가
#### insert 함수 
특정 인덱스(두 번째 파라미터)에 원하는 배열을 삽입
#### delete 함수 
원하는 부분을 삭제

In [15]:
arr = np.array([11,22,33,44,55])

print(np.append(arr,[100,200])) 
print(np.insert(arr,1,[1,2])) # 1번째 인덱스로 [1,2] 추가

print(np.delete(arr, [0,2])) # 0(11), 2(33)번째 삭제

[ 11  22  33  44  55 100 200]
[11  1  2 22 33 44 55]
[22 44 55]


## where(), select() 사용
- 특정 조건을 만족하는 것을 선택하는 용도
- If 문하고 비슷
- select(조건, 바꾸고싶은내용)

In [16]:
arr = np.array([11,130,370,11,44,94,200,30,190])

print(np.where(arr < 100)) # index
print(np.where(arr > 100, 'A', 'B'))

conList = [arr > 200, arr >100, arr >0]
choiceList = ['A', 'B', 'C']
print(np.select(conList,choiceList))

(array([0, 3, 4, 5, 7], dtype=int64),)
['B' 'A' 'A' 'B' 'B' 'B' 'A' 'B' 'A']
['C' 'B' 'A' 'C' 'C' 'C' 'B' 'C' 'B']


## sort()
정렬을 하기 위해서 사용
#### argsort() 라는 함수는, 
sort 한 후 값이 아닌 index를 반환


In [17]:
arr = np.array([44,11,55,22,33])

print(np.sort(arr))
print(np.sort(arr[::-1]))

# arg는 index 변환함수. argsort는 sort한 후 값이 아닌 인덱스 변환 
print(np.argsort(arr))

[11 22 33 44 55]
[11 22 33 44 55]
[1 3 4 0 2]


## argmin(), argmax(), std(), median()
- 기초 통계용 함수
- 중앙값은 평균이 아닌, 해당 값들 중에서 제일 중앙에 위치한 값
- (참고: 평균은 mean())
- 4분위수는, ¼, ½, ¾ 에 해당하는 값

In [18]:
arr = np.array([22,11,44,33,55])

print(arr.min()) 
print(arr.max()) 

print(arr.argmin()) # 가장 작은 값의 인덱스 변환
print(arr.argmax()) # 가장 큰 값의 인덱스 변환

print(arr.std()) # 표준 편차

# 데이터를 정렬했을때 가운데 값 (= 중앙값)
print(np.median(arr))

# 1사분위수(0.25), 중앙값(0.5), 3사분위수(0.75) 값을 변환
print(np.quantile(arr, [0.25, 0.5, 0.75]))

11
55
1
4
15.556349186104045
33.0
[22. 33. 44.]


## 넘파이 응용 예 #1
연봉데이터 salary에서 각 연봉에 대한 세금 3.3%를 제외한 실수령액을 구하는 프로그램

In [19]:
from unittest import result

salary = np.array([1000,2000,3000,4000,5000])

result = salary - salary * 0.033
print(result)

[ 967. 1934. 2901. 3868. 4835.]


## 넘파이 응용 예 #2
name에서 '철' 글자가 있는 데이터를 구하는 프로그램

In [20]:
name = np.array(['홍길동','김철수','임꺽정','김철이','이황'])

for n in name:
    if '철' in n :
        print(n)

김철수
김철이


## 넘파이 응용 예 #3
find() 을 이용해서 원하는 것을 찾을 수도 있음. 특정 인덱스를 가지고 올 수도 있음. 예를들어 ‘홍길동＇ 중에 ‘동 ‘은 2번째 index

In [21]:
name = np.array(['홍길동','김철수','임꺽정','김철이','철이임'])

# '철' 이없으면 -1 반환 & '철'이 있으면 인덱스 반환
print(np.char.find(name,'철'))

# np.char.find(name, '철') ! = -1 이므로 '철'을 포함하는 값의 인덱스 반환 
print(name[np.char.find(name, '철') != -1])

[-1  1 -1  1  0]
['김철수' '김철이' '철이임']


## 넘파이 응용 예 #4
1. 점수가 가장 큰 값을 구하시오
2. 점수가 80점 이상인 값을 구하시오
3. 점수가 50점 이상 80 이하인 값을 구하시오
4. 점수의 평균을 구하시오
5. 점수의 총합을 구하시오

In [22]:
kor = np.array([60,55,70,30,20,90])


print(np.min(kor)) # kor.min() X #1
print(kor[kor >= 80]) #2
print(kor[(kor >=50) & (kor <=80)]) #3
print(kor.mean()) #4
print(kor.sum()) #5

20
[90]
[60 55 70]
54.166666666666664
325


6. 국어 점수가 40점 이하인 데이터를 삭제하시오
7. 국어 점수가 50점 이상인 데이터에 가산점 10%를 부여하시오
8. 국어 점수 top 2를 구하시오
9. 국어 점수가 70점 이상이면 '합격', 아니면 '불합격'으로 국어 점수와 함께 출력하시오

In [23]:
kor = np.array([60,55,70,30,20,90])

print(np.delete(kor, np.where(kor <=40))) #6

kor[kor>=50] = kor[kor>=50] * 1.1
print(kor) #7

sorted_kor = np.sort(kor)
print(sorted_kor)
print(sorted_kor[-2:]) #8

for i in range(len(kor)): #9
    if kor[i] >= 70:
        print(kor[i], '합격')
    else:
        print(kor[i], '불합격')

[60 55 70 90]
[66 60 77 30 20 99]
[20 30 60 66 77 99]
[77 99]
66 불합격
60 불합격
77 합격
30 불합격
20 불합격
99 합격
