## Pandas 

In [1]:
import pandas as pd
import numpy as np

## DataFrame 시작
앞서 언급했던 것 처럼, pandas는 series와 dataFrame이라는 구조를 이용함

In [2]:
# DataFrame 시작
d1 = [[1,2],[3,4],[5,6]]
d2 = [(1,2),(3,4),(5,6)]
d3 = [{'kor' : 1, 'eng' : 2},
      {'kor' : 3, 'eng' : 4},
      {'kor' : 5, 'eng' : 6}]
d4 = {'kor' : [1,3,5], 'eng' :[2,4,6]}

df1 = pd.DataFrame(d1, index=['a','b','c'], columns=['eng', 'kor'])
print(df1)
print("----------------")
df2 = pd.DataFrame(d2)
print(df2)
print("---------------")
df3 = pd.DataFrame(d3)
print(df3)
print("---------------")
df4 = pd.DataFrame(d4)
print(df4)

   eng  kor
a    1    2
b    3    4
c    5    6
----------------
   0  1
0  1  2
1  3  4
2  5  6
---------------
   kor  eng
0    1    2
1    3    4
2    5    6
---------------
   kor  eng
0    1    2
1    3    4
2    5    6


## DataFrame 속성 #1

In [3]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}

df = pd.DataFrame(data, index=['a','b','c','d'])
print(df)
print('--------------')
print(df.ndim) # 차원
print(df.shape) # (행, 열)
print(df.shape[0]) # 행의 개수

print(df.size) # 데이터 개수
print(df.T) # transpose

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
--------------
2
(4, 3)
4
12
       a   b   c   d
eng   10  30  50  70
kor   20  40  60  80
math  90  50  20  70


## DataFrame 속성 #2

In [4]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}

df = pd.DataFrame(data, index=['a', 'b','c','d'])
print(df)
print('-------------------')
print(df.index)
print(df.keys())
print(df.columns)
print('-------------------')
print(df.values)
print(df.dtypes)
print(df.dtypes['eng'])
print('-------------------')
print(df.info())

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
-------------------
Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['eng', 'kor', 'math'], dtype='object')
Index(['eng', 'kor', 'math'], dtype='object')
-------------------
[[10 20 90]
 [30 40 50]
 [50 60 20]
 [70 80 70]]
eng     int64
kor     int64
math    int64
dtype: object
int64
-------------------
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   eng     4 non-null      int64
 1   kor     4 non-null      int64
 2   math    4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes
None


## DataFrame indexing #1

In [5]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('-----------------')
print(df['eng'])
print(df[['eng', 'math']])
print(df['eng']['a':'c'])

print(df[1:3])
print(df['b' : 'c'])

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
-----------------
a    10
b    30
c    50
d    70
Name: eng, dtype: int64
   eng  math
a   10    90
b   30    50
c   50    20
d   70    70
a    10
b    30
c    50
Name: eng, dtype: int64
   eng  kor  math
b   30   40    50
c   50   60    20
   eng  kor  math
b   30   40    50
c   50   60    20


## DataFrame indexing #2

In [6]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])

print(df)
print('--------------------')
print(df.iloc[0])
print(df.iloc[0,0])
print(df.iloc[[0,2,3]]) # 0, 2, 3번 행
print(df.iloc[1:, 1])
print(df.iloc[1:,1:])
print(df.iloc[1:3, [0,2]]) # 2, 3번행 과 0,2번 열

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
--------------------
eng     10
kor     20
math    90
Name: a, dtype: int64
10
   eng  kor  math
a   10   20    90
c   50   60    20
d   70   80    70
b    40
c    60
d    80
Name: kor, dtype: int64
   kor  math
b   40    50
c   60    20
d   80    70
   eng  math
b   30    50
c   50    20


## DataFrame indexing #3

In [7]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])

print(df)
print('-----------------')
print(df.loc['a':'c'])
print(df.loc[['a','c','d']])
print(df.loc['b':])
print(df.loc['b':, 'kor':])
print(df.loc['b':'c', ['eng','math']])

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
-----------------
   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
   eng  kor  math
a   10   20    90
c   50   60    20
d   70   80    70
   eng  kor  math
b   30   40    50
c   50   60    20
d   70   80    70
   kor  math
b   40    50
c   60    20
d   80    70
   eng  math
b   30    50
c   50    20


## DataFrame 산술연산 #1

In [8]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('------------')
print(df + 1)
print(df * 2)
print('--------------------')
df['eng'] = [1,2,3,4]
print(df)
print('-------------')
df['eng'] += 2
print(df)
print('--------------')
df.loc['a'] +=2
print(df)
print('-----------------')
df.loc['b':'c', 'kor':] = [[1,2], [3,4]]
print(df)
print('---------------')
df.loc['b':'c', 'kor':] +=2
print(df)

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
------------
   eng  kor  math
a   11   21    91
b   31   41    51
c   51   61    21
d   71   81    71
   eng  kor  math
a   20   40   180
b   60   80   100
c  100  120    40
d  140  160   140
--------------------
   eng  kor  math
a    1   20    90
b    2   40    50
c    3   60    20
d    4   80    70
-------------
   eng  kor  math
a    3   20    90
b    4   40    50
c    5   60    20
d    6   80    70
--------------
   eng  kor  math
a    5   22    92
b    4   40    50
c    5   60    20
d    6   80    70
-----------------
   eng  kor  math
a    5   22    92
b    4    1     2
c    5    3     4
d    6   80    70
---------------
   eng  kor  math
a    5   22    92
b    4    3     4
c    5    5     6
d    6   80    70


## DataFrame 산술연산 #2

In [9]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('----------------')

print(df[df['eng']> 30])
print(df[(df['kor']==20) | (df['kor']==60)])
print(df[(df['kor']>=20) & (df['kor']<=60)])
print(df[df['kor'].isin([20,40])])

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
----------------
   eng  kor  math
c   50   60    20
d   70   80    70
   eng  kor  math
a   10   20    90
c   50   60    20
   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
   eng  kor  math
a   10   20    90
b   30   40    50


## DataFrame 산술연산 #3

In [10]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('----------------')
print(df.query('eng>30')) # df[df['eng']>30]
print(df.query('kor==20 or kor ==60'))
print(df.query('20<=kor<=60'))
# num = 30
# print(df.query(f'eng>{num}')) # 'eng>{}'.format(num)

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
----------------
   eng  kor  math
c   50   60    20
d   70   80    70
   eng  kor  math
a   10   20    90
c   50   60    20
   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20


## DataFrame 추가 수정 삭제 검색 정렬 #1

In [11]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('----------------')
df['my1'] = [1,2,3,4] # 컬럼이 있으면 수정, 없으면 추가
df['my2'] = df['kor'] + df['eng']
print(df)
print('---------------')
df.loc['e'] = [1, 2, 3, 5, 6] 
print(df)
print('-----------------')
print(df.drop(index=['a', 'c']))
print(df.drop(columns=['eng', 'math']))
print('---------------')
print(df)
df.loc['b':'c', 'kor'] = np.nan
df.loc['c':'d', 'kor'] = np.nan
print(df)
print(df.isna())
print(df.isna().sum())

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
----------------
   eng  kor  math  my1  my2
a   10   20    90    1   30
b   30   40    50    2   70
c   50   60    20    3  110
d   70   80    70    4  150
---------------
   eng  kor  math  my1  my2
a   10   20    90    1   30
b   30   40    50    2   70
c   50   60    20    3  110
d   70   80    70    4  150
e    1    2     3    5    6
-----------------
   eng  kor  math  my1  my2
b   30   40    50    2   70
d   70   80    70    4  150
e    1    2     3    5    6
   kor  my1  my2
a   20    1   30
b   40    2   70
c   60    3  110
d   80    4  150
e    2    5    6
---------------
   eng  kor  math  my1  my2
a   10   20    90    1   30
b   30   40    50    2   70
c   50   60    20    3  110
d   70   80    70    4  150
e    1    2     3    5    6
   eng   kor  math  my1  my2
a   10  20.0    90    1   30
b   30   NaN    50    2   70
c   50   NaN    20    3  110
d   70   NaN    70    4  150
e    1  

## DataFrame 추가 수정 삭제 검색 정렬 #2

In [12]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('----------------')
df.loc['b':'c','kor'] = np.nan
df.loc['c':'d','math'] = np.nan
print(df)
print(df.fillna(1))
df['kor'] = df['kor'].fillna(3)

print(df)
print('------------------')
print(df.dropna())
print(df.dropna(axis=1))
print(df.dropna(subset=['math']))


   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
----------------
   eng   kor  math
a   10  20.0  90.0
b   30   NaN  50.0
c   50   NaN   NaN
d   70  80.0   NaN
   eng   kor  math
a   10  20.0  90.0
b   30   1.0  50.0
c   50   1.0   1.0
d   70  80.0   1.0
   eng   kor  math
a   10  20.0  90.0
b   30   3.0  50.0
c   50   3.0   NaN
d   70  80.0   NaN
------------------
   eng   kor  math
a   10  20.0  90.0
b   30   3.0  50.0
   eng   kor
a   10  20.0
b   30   3.0
c   50   3.0
d   70  80.0
   eng   kor  math
a   10  20.0  90.0
b   30   3.0  50.0


## DataFrame 추가 수정 삭제 검색 정렬 #3

In [13]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('----------------')
print(df.sort_values(by='math'))
print(df.sort_values(by='math', ascending=False))
print(df.sort_values(by=['kor','eng'], ascending=False))
print(df.sort_index())
df.loc['c','kor'] = 40
print(df)



   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
----------------
   eng  kor  math
c   50   60    20
b   30   40    50
d   70   80    70
a   10   20    90
   eng  kor  math
a   10   20    90
d   70   80    70
b   30   40    50
c   50   60    20
   eng  kor  math
d   70   80    70
c   50   60    20
b   30   40    50
a   10   20    90
   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
   eng  kor  math
a   10   20    90
b   30   40    50
c   50   40    20
d   70   80    70


## DataFrame 통계 #1
sum, mean은 axis=1일 때 행

In [14]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('----------------')

print(df.min())
print(df.sum())
print(df.sum(axis=1)) # 행
print(df.sum().sum())
print(df.mean())
print(df.mean(axis=1).round(2))

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
----------------
eng     10
kor     20
math    20
dtype: int64
eng     160
kor     200
math    230
dtype: int64
a    120
b    120
c    130
d    220
dtype: int64
590
eng     40.0
kor     50.0
math    57.5
dtype: float64
a    40.00
b    40.00
c    43.33
d    73.33
dtype: float64


## DataFrame 통계 #2

In [15]:
data = {'eng' : [10, 30, 50, 70],
        'kor' : [20, 40, 60, 80],
        'math' : [90, 50, 20, 70]}
df = pd.DataFrame(data, index=['a' ,'b', 'c', 'd'])
print(df)
print('----------------')

print(df.idxmax())
print(df.idxmax(axis=1))
print(df.median())
print(df.std())
print(df.quantile([0.25,0.5,0.75]))
print(df.count())
print(df.describe())
print(df.describe()['eng'])

   eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70
----------------
eng     d
kor     d
math    a
dtype: object
a    math
b    math
c     kor
d     kor
dtype: object
eng     40.0
kor     50.0
math    60.0
dtype: float64
eng     25.819889
kor     25.819889
math    29.860788
dtype: float64
       eng   kor  math
0.25  25.0  35.0  42.5
0.50  40.0  50.0  60.0
0.75  55.0  65.0  75.0
eng     4
kor     4
math    4
dtype: int64
             eng        kor       math
count   4.000000   4.000000   4.000000
mean   40.000000  50.000000  57.500000
std    25.819889  25.819889  29.860788
min    10.000000  20.000000  20.000000
25%    25.000000  35.000000  42.500000
50%    40.000000  50.000000  60.000000
75%    55.000000  65.000000  75.000000
max    70.000000  80.000000  90.000000
count     4.000000
mean     40.000000
std      25.819889
min      10.000000
25%      25.000000
50%      40.000000
75%      55.000000
max      70.000000
Name: eng, dtype: float64


## DataFrame 통계 groupby #1
CSV(Comma - Separated Values): 각각의 데이터 값을 콤마(,)로 구분하는 파일 형식 (엑셀과 메모장에서 확인)

In [16]:
df = pd.read_csv("../../hotel.csv", index_col=0) # encoding="cp949" 에러 나면 

print(df.head()) # 위에 다섯개
print('----------------------')
print(df['grade'].unique())
print(df['grade'].value_counts().sort_index())
print('----------------------')


g = df.groupby('grade')
print(g.sum()[['price']])

print(g.mean()[['price']])
print(g.max()[['price']])
print(g.count()[['price']])
# print(g.sum()[['rate']])

     grade  rate  price
호텔1     10     1   9500
호텔2      8     2   8000
호텔3      6     4   6000
호텔4      9     2   8600
호텔5      7     4   7000
----------------------
[10  8  6  9  7  5]
5     6
6     2
7     3
8     5
9     2
10    2
Name: grade, dtype: int64
----------------------
       price
grade       
5      25300
6      12800
7      21200
8      41300
9      17400
10     18800
             price
grade             
5      4216.666667
6      6400.000000
7      7066.666667
8      8260.000000
9      8700.000000
10     9400.000000
       price
grade       
5       5200
6       6800
7       7100
8       8500
9       8800
10      9500
       price
grade       
5          6
6          2
7          3
8          5
9          2
10         2


## DataFrame 통계 groupby #2
CSV(Comma - Separated Values): 각각의 데이터 값을 콤마(,)로 구분하는 파일 형식

In [17]:
df = pd.read_csv('../../hotel.csv', index_col=0)

g = df.groupby('grade')

mydf = g.agg(['sum', 'mean', 'count'])['price']
mydf.columns = ['가격의 총합', '가격의 평균', '가격의 개수']
print(mydf)

       가격의 총합       가격의 평균  가격의 개수
grade                             
5       25300  4216.666667       6
6       12800  6400.000000       2
7       21200  7066.666667       3
8       41300  8260.000000       5
9       17400  8700.000000       2
10      18800  9400.000000       2
